services:
  ping-pong-bot:
    restart: always
    # Give plenty of time to finish the iteration. Mempool scanning can take a while
    stop_grace_period: 10m
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file: .env
    volumes:
      - ./data:/usr/src/app/data
